--This file defines filepaths which define the layout of the solution generated by premake

ROOT_PATH			= path.getabsolute("..").."/"
SOLUTION_PATH		= ROOT_PATH
PROJECT_PATH		= ROOT_PATH.."vs_projects/"
FILES_PATH			= ROOT_PATH.."files/"
THIRD_PARTY_PATH	= ROOT_PATH.."thirdparty/"
BINARY_PATH			= ROOT_PATH.."bin/"
INTERMEDIATE_PATH	= ROOT_PATH.."intermediate/"
OVERRIDE_PATH		= "overrides/"