--This file defines filepaths which define the layout of the solution generated by premake

ROOT_PATH			= path.getabsolute("..").."/"
GENERATED_PATH		= ROOT_PATH.."generated_files/"
FILES_PATH			= ROOT_PATH.."files/"
THIRD_PARTY_PATH	= ROOT_PATH.."thirdparty/"
OVERRIDE_PATH		= ROOT_PATH.."premake/overrides/"
SOLUTION_PATH		= GENERATED_PATH
PROJECT_PATH		= GENERATED_PATH.."vs_projects/"
BINARY_PATH			= GENERATED_PATH.."bin/"
INTERMEDIATE_PATH	= GENERATED_PATH.."intermediate/"